### ISSUE TITLE
bug: replay recorded SDK session leads to FileNotFoundError exception being raised

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub-sdk-python#64]
### Component

Python SDK

### Infrahub SDK version

0.14.0

### Current Behavior

When you try to replay an SDK session, it seems that we are looking for an incorrect filename (or the recorded query response is stored with the wrong filename) due to which the replay fails with a FileNotFoundError exception.

### Expected Behavior

The correct filename would be used to lookup the output of a replayed session, or the output of a recorded query is stored with the correct filename.

### Steps to Reproduce

- load an instance of infrahub
- load the demo schema and data
- run the following script to record the session, set the environment variable `INFRAHUB_JSON_RECORDER_DIRECTORY` to a directory of preference
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync(config=Config(recorder="json"))
client.get("InfraDevice", name__value="atl1-edge1")
```
- then set the environment variable `INFRAHUB_PLAYBACK_DIRECTORY` to the same value as `INFRAHUB_JSON_RECORDER_DIRECTORY`
- execute the following  script
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync(config=Config(transport="json"))
client.get("InfraDevice", name__value="atl1-edge1")
```

**Comment by ogenstad** [comment]
I looked at this, didn't think anything had changed here but there's a change that was made quite some time ago with regards to how we determine what the expected content should be if we look back at an earlier version of the SDK we can see that this line has changed:

https://github.com/opsmill/infrahub/blob/infrahub-v0.10.0/python_sdk/infrahub_sdk/playback.py#L48

What we currently have:
```python
    def _read_request(
        self,
        url: str,
        method: HTTPMethod,
        headers: dict[str, Any],
        timeout: int,  # pylint: disable=unused-argument
        payload: Optional[dict] = None,
    ) -> httpx.Response:
        content: Optional[bytes] = None
        if payload:
            content = str(ujson.dumps(payload)).encode("utf-8")
        request = httpx.Request(method=method.value, url=url, headers=headers, content=content)

        filename = generate_request_filename(request)
```

So what happens is that we do a hash of the content in order to figure out what file to load and this hash will be different if we dump the content with `ujson` instead of `json`. Reverting to just `json` should work here and I think that should be the quick fix. Later we might want to consider to run the content from the recording phase through ujson as well (this is to protect against future changes from within httpx).

For a short while we had this running in some of the unittests for Infrahub itself but after that we redid how the tests are executed making it easy to run against "live" data. But we should also add some tests around this once we can enable the integration tests again in the SDK repo and also add some docs around it.
